OpenVR-Advanced-Settings/OpenVR-AdvancedSettings

advancedSettings.pro, src/main.cpp, src/overlaycontroller.cpp, src/overlaycontroller.h, src/tabcontrollers/AccessibilityTabController.cpp, src/tabcontrollers/AudioTabController.cpp, src/tabcontrollers/ChaperoneTabController.cpp, src/tabcontrollers/FixFloorTabController.cpp, src/tabcontrollers/MoveCenterTabController.cpp, src/tabcontrollers/ReviveTabController.cpp, src/tabcontrollers/SettingsTabController.cpp, src/tabcontrollers/StatisticsTabController.cpp, src/tabcontrollers/SteamVRTabController.cpp, src/tabcontrollers/SteamVRTabController.h, src/tabcontrollers/UtilitiesTabController.cpp, src/tabcontrollers/audiomanager/AudioManagerDummy.cpp, src/tabcontrollers/audiomanager/AudioManagerWindows.cpp, src/tabcontrollers/keyboardinput/KeyboardInputDummy.cpp, src/tabcontrollers/keyboardinput/KeyboardInputWindows.cpp
Treating warnings as errors ensures that important compiler warnings aren't ignored.
With relatively few fixes, the /WX switch on MSVC and the -Werror switch on GCC/Clang can be enabled.
It is worth noting that GCC/Clang have a significantly larger amount of warnings than MSVC on /W3. It is not feasible to enable the /W4 (warning level 4, current is 3) switch on MSVC yet, since a very large amount of warnings are from third party files. Finding a solution to this should bring MSVC warning levels up to parity with GCC/Clang.
Compiling with clang-cl.exe on Windows still gives a large amount of errors. Most of them from the third party `easylogging++.h` file. The rest are relatively easy `-Wmismatched-new-delete` and `-Wmissing-braces` warnings. There are also still large amount of old C …
=> Add compiler switches for treating warnings as errors, fix current warnings

src/tabcontrollers/PttController.cpp
Improved the trigger binding for push to talk on Valve Knuckles controllers by removing the "touched" condition. The capacitive touch sensor on the knuckles caused a hair-trigger that didn't feel right.
=> Improved Valve Knuckles PTT trigger feel

src/res/qml/AudioPage.qml
When audio devices connected or disconnected from the system, the default audio device swapped around. This was because of QML setting index 0 on ComboBox.model changes. onCurrentIndexChanged was calling setPlaybackDeviceIndex() / mirrorDevice/ micDevice etc... in the audio tab controller and actively setting the audio device index to 0 momentarily. Changing onCurrentIndexChanged to onActivated allows the ComboBox to only actively command the audio tab controller in direct response to user interaction.
=> Fixed audio devices swapping on device hw changes

src/main.cpp, src/overlaycontroller.cpp, src/overlaycontroller.h, src/tabcontrollers/ReviveTabController.cpp
For the reasons outlined in #29 the OverlayController has been implemented as a RAII object.
The `Init` function has been moved to the constructor, removing a necessary function call for full construction.
Notice that in order to fully work the `void OverlayController::SetWidget` function must still be called to properly construct the object. This is a limitation due to `quickObj` in main being created after the constructor is called. Further refactoring should probably look at splitting the constructor into more specific functions, and folding `void OverlayController::SetWidget`  into the constructor.
Notice also in the constructor that a function `static` variable has been declared holding the address of the OverlayController. This is obviously a disgusting thing to do, but the …
=> Refactor OverlayController to be implemented as RAII object instead of global singleton

advancedSettings.pro, src/res/qml/LineSeparator.qml, src/res/qml/UtilitiesPage.qml, src/res/qml/media_keys/MediaButton.qml, src/res/qml/media_keys/MediaControllerKeys.qml, src/res/qml/media_keys/outline_pause_white_24dp.svg, src/res/qml/media_keys/outline_play_arrow_white_24dp.svg, src/res/qml/media_keys/outline_play_pause_white_24dp.svg
The old QML was a giant mess of implementation details and logic.
Reducing the buttons to only 2 essential properties allows the MediaControllerKeys object to be more easily understood.
Moving the MediaControllerKeys into its own QML file allows the resulting page to be more easily understood and individual pieces swapped in and out.
The current QML directory structure is non-existent, breaking parts down into cohesive folders will allow for easier understanding of the bigger picture.
=> Refactor Media Control Keys QML into smaller bits

build_scripts/win/common.py, installer/installer.nsi, src/overlaycontroller.h
Since version strings are displayed in logs and on the main screen, this
will prevent situations where the master branch is confused with the
2.8.0-release branch.
The 2-8-0-release file was a one time thing because the version numbers
were already changed, it should not be created for future releases.
=> Rename version strings to 2.8.0-dev

advancedSettings.pro, src/overlaycontroller.cpp, src/overlaycontroller.h, src/overlaycontroller/openvr_init.cpp, src/overlaycontroller/openvr_init.h
The OpenVR init code is currently being run in the OverlayController constructor. Member objects that are initialized before the
OverlayController (ideally all of them) can't use OpenVR APIs before the first line of the OverlayController constructor. Implementing the OpenVR Init code as a class means that it is able to initialize before all the other objects and allow them to use OpenVR APIs in their constructors.
The class has been placed in a folder called "overlaycontroller" to signify that it should only be used by the OverlayController.
openvr_init.h uses `#pragma once` despite it being unofficial since it is supported on all modern compilers.
The copy constructor, copy assignment operator, move constructor and move assignment operator have  been explicitly deleted in order to make …
=> Refactor OpenVR init code to separate class

src/res/qml/AudioPage.qml, src/tabcontrollers/AudioTabController.cpp, src/tabcontrollers/AudioTabController.h
- Fixed Issue #19 Audio profiles now properly display on start-up
- Fixed Issue #45 Re-named a function to allow better read-ability
=> fixed default audio profile display

src/tabcontrollers/audiomanager/AudioManagerWindows.cpp
When the vive pro wireless adapter loses connection, its audio devices are
removed, causing an OnDefaultDeviceChanged event to be issued for each
such device that was previously set as the default. However, if no other
device is available for the role that was disconnected (e.g. if the Vive
Pro was providing the only system microphone), then pwstrDefaultDeviceId
is NULL.
In this case, we would invoke getDevice on the NULL device ID, then
attempt to print the default device name in the debug logging path; this
NULL dereference would cause AdvancedSettings to crash.
This change simply fixes the logging code to not attempt to print the
new default device name when it is NULL.
=> Fix NULL dereference in OnDefaultDeviceChanged

src/tabcontrollers/ChaperoneTabController.cpp
ChaperoneTab's flipOrentation() calls RotateUniverseCenter() and should reset the universe offsets first. Not doing so might have unexpected behaviors.
=> ChaperoneTab flipOrentation should reset offsets

.appveyor.yml, .travis.yml, docs/building_for_windows.md
The 5.11.2 version has been removed from AppVeyor leading to all builds failing due to lack of Qt install. The  5.12 folder is symlinked to the newest Qt 5.12 version, preventing the need for changes during small updates and preventing failures when versions have been removed.
This solves issue #53.
Additionally, it makes the Travis CI instance spit out the current Qt version with `qmake --version`.
=> Update to qt5.12

.clang-tidy, .gitattributes, .travis.yml, Readme.md, build_scripts/linux/build_linux.sh, build_scripts/linux/format.sh, build_scripts/linux/run-clang-tidy.sh, build_scripts/linux/verify_formatting.sh, docs/building_for_linux.md, installer/installer.nsi
* Adds clang-tidy checks for everything that does not currently produce warnings.
* Updates the Linux build scripts.
* Fixes Travis CI instances outputting the version of the wrong compiler.
* Fixes typo in `.gitattributes` that did not apply `LF` endings to `.sh` files.
* Fixes #80.
* The `.clang-tidy` file specifies which checks are enabled. Right now all (`*`) checks are enabled, except those that are explicitly disabled with minus.
* All `.cpp` files are checked. The `easylogging++.cc` file is therefore not checked, but calls from other files to this file will still warn.
* A third Travis CI instance will handle `clang-tidy`. The program responsible for creating the compilation database (`bear`) is not available for Windows. Therefore Windows specific code will not be tested.
* `make` …
=> Add clang-tidy, update Linux build scripts

src/overlaycontroller.cpp
The old shutdown code did not correctly exit but instead just continuously called the QApplication notify function until it SEGFAULTed. This led to crashes whenever SteamVR was shut down. Users with Windows Error Reporting turned on would get a 100+ MB crashdump file along with increased shutdown time for SteamVR. 
For clarity the shutdown functions should probably be collected in a
single function in the future.
This fixes #89.
=> Add proper exit to shutdown code

build_scripts/qt/sources.pri, src/openvr/ivrinput.cpp, src/openvr/ivrinput.h, src/openvr/ivrinput_action.h
This errors at compile time if the wrong action is being used instead of at runtime.
This is a part of #111.
=> Create DigitalAction and AnalogAction types to replace the Action

src/res/qml/audio_page/dialog_boxes/AudioNewProfileDialog.qml
* Fixes #105.
* The offset is applied with specific X/Y coordinates instead of changing the parent component since this keeps the associated elements contained.
=> Move audio profile popup to center of screen

build_scripts/qt/resources.pri, src/openvr/ivrinput.cpp, src/openvr/ivrinput.h, src/overlaycontroller.cpp, src/overlaycontroller.h, src/package_files/action_manifest.json, src/res/qml/motion_page/MotionPage.qml, src/res/qml/motion_page/gravity/GravityGroupBox.qml, src/res/qml/motion_page/space_drag/SpaceDragGroupBox.qml, src/res/qml/motion_page/space_turn/SpaceTurnGroupBox.qml, src/tabcontrollers/MoveCenterTabController.cpp, src/tabcontrollers/MoveCenterTabController.h
**This update adds the following gravity options to the Motion tab:**
- "On" checkbox: enables disables gravity without the need for action bind.
- Gravity Strength: downward acceleration in m/s^2.
- Planet buttons: easy setting of gravity strengths.
- Save Momentum checkbox: when unchecked momentum is reset every time gravity is enabled.
- Fling Strength: Multiplier on velocity gained from space drag.
**The following action was added:**
- Gravity Reverse:
(non-toggle / holdable) When held, gravity strength is multiplied by -1. When gravity strength is negative it's possible to pass through the floor level, and the user is always considered in the "falling" state with negative gravity strength.
**Additional Notes:**
This update also prevents dynamic motion for occurring when the overlay …
=> Implement gravity options and ui

src/package_files/action_manifest.json, src/res/qml/PlayspacePage.qml, src/res/qml/motion_page/MotionPage.qml, src/res/qml/motion_page/gravity/GravityGroupBox.qml, src/res/qml/motion_page/height_toggle/HeightToggleGroupBox.qml, src/res/qml/motion_page/snap_turn/SnapTurnGroupBox.qml, src/tabcontrollers/MoveCenterTabController.cpp, src/tabcontrollers/MoveCenterTabController.h
**Added:**
- Snap-turn angle buttons to the motion tab
- Fling strength 1x, 2x, 3x, 4x buttons
**Removed:**
-  non-functional left over elements from the offsets tab
=> Clean up offsets ui and add snap turn settings

src/utils/setup.cpp
The `QMessageLogContext` is only filled out in debug builds. Release builds will have null pointers in `file` and `line`. This causes any error attempted to be logged to result in a null pointer dereference.
Since we never use debug builds anyway, simply removing the uses of `file` and `line` makes sense.
Github issue
https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/issues/139
Fixes #139.
=> Fix null pointer dereference in QtMessageHandler function

src/overlaycontroller.cpp, src/overlaycontroller.h, src/res/qml/PlayspacePage.qml, src/res/qml/SettingsPage.qml, src/tabcontrollers/MoveCenterTabController.cpp, src/tabcontrollers/MoveCenterTabController.h, src/utils/ChaperoneUtils.cpp, src/utils/ChaperoneUtils.h
Addresses: #145 and #148  (proximity warning not addressed)
This pull requests implements the necessary considerations for universe types other than standing.
- Raw universe detection is added and actions taken such that room setup is properly applied.
- Seated universe is detected and the seated universe coordinate system has now been implemented into Advanced Settings.
- Added seated recenter button to offsets tab.
In order for seated recenter to mesh well with Advanced Settings the recenter function applies the hmd's position and angle as offsets to recenter the playspace. These offsets are visible and editable in the offsets tab.
- Added "Allow External App Chaperone Edits" checkbox to the settings tab. Off by default
This setting allows external modifications to the chaperone to be …
=> Implement Seated Universe and Raw (Room Setup) Universe Support

src/tabcontrollers/MoveCenterTabController.cpp
This should (hopefully) fix the remaining instances where chaperone warnings could miss being updated to reference the current chaperone position. (#152)
=> Fix chaperone updates not updating chaperone warnings reference

.clang-tidy, .travis.yml, advancedSettings.pro, build_scripts/linux/build_linux.sh, build_scripts/linux/configure.sh, build_scripts/qt/compilers/clang.pri, build_scripts/qt/sources.pri, build_scripts/win/common.py, docs/building_for_linux.md, docs/building_for_windows.md
This is mostly changes for Linux, since the CI for Windows is already on 5.12.
On Windows there was already a soft requirement for 5.12, since QMAKE did not recognize the C++17 flag for MSVC, leading to compile errors.
On Linux there was a soft requirement for 5.7 at runtime.
The majority of this is just documentation for building on Linux and getting the Linux CI working with 5.12, since the packages are needed from a third party repository.
The Linux part has been tested as working on Windows Subsystem for Linux Ubuntu 18.04 and the Ubuntu 16.04 Travis CI.
Getting docs for non-Ubuntu systems would be great.
Fixes #137.
=> Update required Qt version to 5.12

.appveyor.yml, .travis.yml, src/openvr/openvr_init.cpp, src/overlaycontroller.cpp, src/tabcontrollers/UtilitiesTabController.cpp, src/utils/setup.cpp
Within the last 24 hours AppVeyor updated to LLVM 8.0.0. For some reason this results in clang-format wanting a different layout.
Since it doesn't seem to be possible to downgrade the AppVeyor version, we'll need to update everything else. In our case our personal machines and the Travis instance.
=> Update Travis CI LLVM to version 8.0.0, fix whitespace issues in upgrading to 8.0.0

.clang-tidy, build_scripts/win/common.py, installer/installer.nsi, src/overlaycontroller.h
Release 3.1.0 PR
###New Features:
- Brightness Adjustment: Finely control your brightness now! (Found in new "Video" tab) - [Ykeara](https://github.com/ykeara)
- Desktop Adjustment: Shift Desktop View Left/Right/Up/Down/Closer/Further, and save that state (easier to use desktop overlay). - [username223](https://github.com/username223)
- New "Seated Recenter" button now visible in Offsets tab when in seated mode applications. - [Kung](https://github.com/Kung-vr)
- Add Ctrl-C and Ctrl-V keyboard shortcuts to the Utilities tab. - [Kung](https://github.com/Kung-vr)
- “Allow External App Chaperone Edits” checkbox (in settings tab) applies adjustments to the chaperone from external sources (only when offsets are zeroed). - [Kung](https://github.com/Kung-vr)
###Bug Fixes:
- Fixed an issue that …
=> Release 3.1.0

build_scripts/linux/build_linux.sh, build_scripts/linux/configure.sh, build_scripts/linux/run-with-library.sh, build_scripts/qt/compilers/gcc.pri, build_scripts/qt/sources.pri, docs/building_for_linux.md, src/tabcontrollers/keyboardinput/KeyboardInput.h, src/tabcontrollers/keyboardinput/KeyboardInputWindows.cpp, src/tabcontrollers/keyboardinput/KeyboardInputX11.cpp
* Adds all KeyboardManager functions for Linux except for the media keys which are probably going to be implemented with [DBUS](https://doc.qt.io/qt-5/qtdbus-index.html) instead of as literal keyboard keys. Progresses #43 with `Send regular keystrokes`.
* Updates hardcoded `g++` version to any at or above version 7. Previously it would only use `g++-7`. Newer versions of Ubuntu ship with `>7`.
* Makes the Linux executable look in the current directory for libraries. This means it is unnecessary to use `LD_LIBRARY_PATH`.
* Updates build script to make Qt Creator `#include`s work correctly on Linux.
* Updates documentation for building on Ubuntu 19.04.
* The implementation for sending user defined strings as keyboard keys is very shoddily implemented. Currently it only supports the [Latin1 …
=> Add partial KeyboardManager for Linux, update build scripts and docs

build_scripts/linux/configure.sh, build_scripts/qt/sources.pri, docs/building_for_linux.md, src/media_keys/media_keys.h, src/media_keys/media_keys_dbus.cpp
* Enables all media keys for use on applications that support DBUS with the MediaPlayer2 interface.
* Partially solves #43.
* The Windows media keys implicitly make every media player perform the required function, there is no way to only target one specific application. The Linux version replicates this, even though finer controls are possible.
* It is also possible to have two way communication between media players and Advanced Settings on Linux. This could be used for displaying currently playing song or other metadata. This does not seem available on Windows in a standardized way.
* Tested on Ubuntu 19.04 (header and cpp file in separate application, not tested from VR with Advanced Settings).
=> Add Linux support for Media Keys with DBUS

src/keyboard_input/input_parser.cpp, src/keyboard_input/input_sender_X11.cpp
Keys were erroneously being sent as `KeySym`s instead of `KeyCode`s.
Additionally, held modifiers also weren't released correctly and numbers were not treated correctly on all platforms.
=> Fix Linux Keyboard Input not working

.circleci/config.yml, build_scripts/linux/configure.sh, build_scripts/linux/run-clang-tidy.sh, build_scripts/qt/compilers/clang.pri, build_scripts/qt/compilers/gcc.pri, docs/building_for_linux.md
* Adds a config file for CircleCI.
* Updates the Linux build process to be more robust (more compiler versions supported).
* Updates documentation for building on Linux.
* Travis and Circle are both running the same versions of software, however automatic updates to the image, ppas or other variables could produce different results.
* It is planned for Travis and CircleCI to both run during a transition period. This is to see if any inconsistencies pop up.
* It has been [heavily](https://www.reddit.com/r/programming/comments/atjltu/layoffs_at_travis_ci_their_team_was_being/) speculated that Travis is taking a turn for the worse. CircleCI was recommended as a replacement.
* Travis does not currently allow us to have it create artifacts in the same way that our AppVeyor setup does, while …
=> Add CircleCI support for Linux, update Linux build process and docs

.circleci/config.yml, build_scripts/linux/appimage.sh, build_scripts/qt/compilers/gcc.pri, docs/building_for_linux.md, src/package_files/linux/AdvancedSettings.desktop
* Makes CircleCI create AppImage executables using GCC.
* Adds a check for `g++-9` to Qmake.
* The AppImage has only been fully tested as working on Ubuntu 19.04. Due to lack of testers it was not possible to test on more distros.
* The CircleCI config file is a mess right now. The GCC and Clang setups do basically the same thing but they're in separate lists because it's not possible in YAML to append to the build steps.
=> Add AppImage artifacts to CircleCI, add g++-9 detection

src/openvr/ivrinput.cpp, src/openvr/ivrinput.h, src/overlaycontroller.cpp, src/package_files/action_manifest.json, src/tabcontrollers/ChaperoneTabController.cpp, src/tabcontrollers/ChaperoneTabController.h
Addresses #244. This adds two actions to the "Haptics" tab of Advanced Settings's steamvr input bindings. "Add Left Haptic Click" and "Add Right Haptic Click". This is intended to remedy the situation on index controllers where the joystick's physical click isn't always felt. It's intended to be bound to "Thumb Stick" use as "BUTTON", "click".
This action could be bound to any controller button to add haptic feedback as well. It will play a different haptic sequence on activation and deactivation of the button.
=> Implement "Add Left/Right Haptic Click" binds

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Having to wait for OPs to respond with details that should have been in the original issue is getting a little annoying.
This will reduce the amount of freeform writing required by people to produce a usable feature request/bug report.
=> Add bug report/feature request issue templates

src/tabcontrollers/ChaperoneTabController.cpp
Having the application call Sync() every frame led to slowdowns on some 4 core CPUs and instant crashes on some older CPUs.
This makes the chaperone velocity modifier only update on every 101st frame. This might not be the ideal framerate, but having it update every frame makes the app crash on start for some users.
On Manjaro with a i7-6700K (4 cores) this led to instant crashes of SteamVR+Steam+OVRAS, with a SEGFAULT in SteamVR.
Issue here:
https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/issues/252
Might also be related to the problem described in https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/issues/255.
This should not be merged before the OP of #252 reports back as it having solved the issue. https://github.com/Zamundaaa @Zamundaaa
=> Reduce update rate of chaperone velocity modifiers

src/overlaycontroller.cpp, src/overlaycontroller.h, src/res/qml/SettingsPage.qml, src/res/qml/audio_page/dialog_boxes/PttNewProfileDialog.qml
This adds a new option to the settings tab to disable vsync (vsync will still default to on for new users). When vsync is disabled a text box for a custom tick rate (default 20ms) will appear. Currently values between 1~999ms are accepted. This addresses #255
=> Add disable vsync and custom tickrate options

src/overlaycontroller.cpp, src/tabcontrollers/AudioTabController.cpp, src/tabcontrollers/AudioTabController.h, src/tabcontrollers/ChaperoneTabController.cpp, src/tabcontrollers/ChaperoneTabController.h, src/tabcontrollers/FixFloorTabController.cpp, src/tabcontrollers/FixFloorTabController.h, src/tabcontrollers/MoveCenterTabController.cpp, src/tabcontrollers/MoveCenterTabController.h, src/tabcontrollers/ReviveTabController.cpp, src/tabcontrollers/ReviveTabController.h, src/tabcontrollers/SettingsTabController.cpp, src/tabcontrollers/SettingsTabController.h, src/tabcontrollers/StatisticsTabController.cpp, src/tabcontrollers/StatisticsTabController.h, src/tabcontrollers/SteamVRTabController.cpp, src/tabcontrollers/SteamVRTabController.h, src/tabcontrollers/UtilitiesTabController.cpp, src/tabcontrollers/UtilitiesTabController.h, src/tabcontrollers/VideoTabController.cpp, src/tabcontrollers/VideoTabController.h
All the original tab controllers used a "design pattern" of giving all controllers a pointer to the Qt window and the OverlayController, even if they didn't need them.
This PR removes the unnecessary members and the entire `initStage2` function for the `VideoTabController`, which was a noop.
=> Remove unnecessary init functions, pointers to widget and parent from tab controllers

docs/keyboard_input_guide.md
The logs are stored in `~/.local/share/AdvancedSettings-Team/OpenVRAdvancedSettings/`, but the config file is stored in `~/.config/AdvancedSettings-Team/`.
=> Update linux input guide config location

advancedSettings.pro, build_scripts/win/build.py, build_scripts/win/common.py, build_windows.cmd
`qmake` is better suited for finding `windeployqt`, since it's in the same directory as `qmake` on windows.
`qmake` is also better suited for finding the build target (release/debug) vs third party scripts.
`windeployqt` is being forced to run in `cmd` because the syntax is different for running executables in powershell, which means `windeployqt` won't be executed and runtime or  package errors will occur.
With the removal of the windeployqt call the deploy step is no longer needed for building on Windows, since all previous deploy tasks are now handle by Qmake.
With this, pressing the build button in Qt Creator will also fully build the project (but not package) leading to better IDE integration.
=> Move windeployqt call from build script to Qmake

.circleci/config.yml, advancedSettings.pro, docs/building_for_linux.md, src/tabcontrollers/ChaperoneTabController.cpp
* Removes unnecessary documentation from building on linux. The rpath is now set to the current directory so script file is no longer necessary or included.
* Reverts the changes to the chaperone velocity modifier. The changes didn't fix the problem on Manjaro and broke the feature for everybody else. Fixes #252.
* Adds the `make install` command for building on Linux. This copies the build directory into `/opt/OpenVR-AdvancedSettings`, acting as a way to use the application in "production" without using the AppImage.
* Downgrades the version of `gcc` used to build the AppImage. The current version used makes the AppImage not work on LTS releases of Ubuntu 18.04 and derivates (Linux Mint 19.1). Fixes #266.
=> Add `make install` to Linux, fix AppImage not working on older distros, revert chaperone changes

Readme.md, advancedSettings.pro, build_scripts/qt/sources.pri, docs/building_for_linux.md
* Updates the Linux build docs to be more true to the Linux way.
* Adds a public Discord button on the readme. Fixes #279 
* Moves the Table of Contents on the readme below the introductory header and image.
* The `build_linux.sh` script previously mentioned in the docs is still being used for CI, due to it being way easier to have control flow in a shell script than in the CI config files.
=> Update Linux build docs, add public Discord link to readme, move TOC

src/overlaycontroller.cpp, src/res/qml/ChaperoneWarningsPage.qml, src/tabcontrollers/ChaperoneTabController.cpp, src/tabcontrollers/ChaperoneTabController.h
fixes #275
Removes the velocity dependent fade feature.
due to performance difficulties, and the fact it makes the platform unstable on some systems, and to fix it would require reducing its effectiveness to being irrelevant.
**Also** changed floating point conversions in ChaperoneTabController.cpp to use a delta value  of > 0.005 rather than exact comparison
=> Velocity fade dependent setting removal

src/res/qml/PlayspacePage.qml, src/res/qml/SettingsPage.qml, src/tabcontrollers/ChaperoneTabController.cpp, src/tabcontrollers/MoveCenterTabController.cpp, src/tabcontrollers/MoveCenterTabController.h
This pull request attempts to further fix buggy behavior with non lighthouse headsets (tested on WMR) when doing a seated recenter. It accomplishes this by sending a recenter request from OVRAS itself any time there is a VREvent detecting a recenter happening. (there's code to prevent an endless loop)
This also adds an option that can be added directly to the ini file: under [playspaceSettings] settings simpleRecenter=true will restore the old functionality of a single recenter rather than the loop back double recenter. However I couldn't notice any jolting behavior even with the double recenter on Vive, so for now I'm leaving this as a direct .ini file option only and defaulting to the new loopback recenter on all HMDs.
=> Seated debug

src/overlaycontroller.cpp, src/overlaycontroller.h, src/res/qml/RootPage.qml, src/res/qml/SettingsPage.qml, ver/versioncheck.json
Addresses #305
This adds the ability to check the github repository for a json file containing information on the latest version. The json can also supply a custom message for when an update is needed as well as an optional message to be displayed even when no update is needed.
This does not do any auto updating. It only checks version numbers and informs the user if a newer one is available.
I've opted for a single enable/disable option in the settings tab for simplicity's sake. I've made the notification an non-obstructive bottom bar on the root tab rather than a pop up, so the desire to disable it's display for clutter's sake should be minimal. The only use case I see for disabling would be for concerns about preventing network connections.
For testing, please edit the …
=> Add version checking feature

Readme.md
Bindings page was deprecated with the API feature of opening the bindings interace.
Fixes #321.
=> Remove bindings page from Readme.md

build_scripts/qt/sources.pri, docs/specs/Settings-API.md, src/main.cpp, src/openvr/overlay_utils.cpp, src/overlaycontroller.cpp, src/settings/bool_setting_value.h, src/settings/double_setting_value.h, src/settings/setting_value.h, src/settings/settings.cpp, src/settings/settings.h, src/settings/settings_controller.h, src/settings/settings_internal.h, src/settings/specific_setting_value.h, src/tabcontrollers/MoveCenterTabController.cpp, src/utils/setup.h
The current solution for storing and getting settings is to directly use the Qt QSettings object.
This leads to extremely verbose code for something that really should just be a single function call.
While the Qt settings management abstracts low level details very well, an even higher level API should be sought after.
The current system has stringly typed settings, which means it's possible to save the `desktopWidth` setting, but attempt to use the `deskWidth` setting somewhere else without noticing.
Currently, there are many different ways for a variable to be initialized depending on what goes wrong (QML, header file initialization, constructor, QSettings loading).
There should only default option when none other are available.
The public facing API should be decoupled from the Qt API, …
=> Add new settings API and convert one function to use new version

src/res/qml/motion_page/gravity/GravityGroupBox.qml, src/settings/internal/settings_controller.h, src/settings/settings.h, src/tabcontrollers/MoveCenterTabController.cpp, src/tabcontrollers/MoveCenterTabController.h
This adds a "friction" feature to the motion tab as per issue #344
When set to "0%" (default) it does nothing, but when larger percentages are used it degrades current velocity depending on the percentage. Degradation is relative to velocity so that it will feel something like wind resistance. When motion is very very small it instead halts velocity.
A value of 100% will bring the user to a full stop within roughly 1 second. The max value is 999% and min is 0%. Most useful values should be found within the range of 20%~80%.
Additionally this PR prevents the new settings api from saving reversed gravity caused by the binding to settings. It instead checks the reversed gravity bind on gravity processing and reverses the strength value within the gravity update function without touching the …
=> Add friction feature to motion tab

build_scripts/qt/sources.pri, docs/specs/Settings-Object-API.md, src/main.cpp, src/settings/internal/settings_object_data.h, src/settings/settings.cpp, src/settings/settings_object.cpp, src/settings/settings_object.h, src/utils/setup.h
The current method of saving logically connected variables is to use the QSettings API directly.
This leads to large amounts of code duplication since every controller has to have their own implementation.
It also leads to slow development since new features will usually have to implement their own settings system.
The API should be resistant to internal changes.
The API should be simple to use.
The API MUST allow the permanent storage of objects. Internal changes to objects MUST NOT be a breaking change.
The public API is in the `settings_object.h` file in the `settings` namespace.
The API consists of two parts, an imperative set of functions and a virtual class that objects must implement.
The imperative functions are straightforward.
```cpp
void saveObject( const ISettingsObject& obj …
```
=> Settings objects

Readme.md, advancedSettings.pro, build_scripts/linux/PKGBUILD, build_scripts/qt/compilers/common-msvc.pri, docs/building_for_linux.md, src/overlaycontroller.cpp, src/utils/setup.cpp
This PR includes PR #350. (Fixes #334).
Additionally it fixes 3 problems with compiling for Qt 5.14.0:
* SEGFAULT immediately after running (Windows and Linux). Fixes #343.
* `COPIES` variable was unable to copy files using the `dir/*` syntax on Windows for an unknown reason.
* Fix MSVC warning C4242 for `qfloat16.h`, which it is not possible to exclude warnings for.
The AppVeyor build will fail due to no artifact storage.
=> Fix several problems when compiling on Qt 5.14.0, add PKGBUILD, and debugSymbols switch

src/main.cpp, src/overlaycontroller.cpp, src/overlaycontroller.h, src/res/qml/RootPage.qml, src/settings/internal/settings_object_data.h, src/settings/settings_object.cpp, src/settings/settings_object.h, src/tabcontrollers/AudioTabController.cpp, src/tabcontrollers/AudioTabController.h, src/tabcontrollers/ChaperoneTabController.cpp, src/tabcontrollers/ChaperoneTabController.h, src/tabcontrollers/MoveCenterTabController.cpp, src/tabcontrollers/MoveCenterTabController.h, src/tabcontrollers/VideoTabController.cpp, src/tabcontrollers/VideoTabController.h, src/tabcontrollers/audiomanager/AudioManagerWindows.cpp
* Required for screenshots.
* `save/loadAllObjects` functions since the implementation can be a little tricky due to off by one errors.
* Automatic type deduction on more things, since strings in C++ in general are weird and annoying.
* Defaults have been moved over as well as I could. I have never used the profile features for anything, so maybe someone with more knowledge of how they should work can spot some weird default values.
* I decided on the `TabController::StructName` syntax as a save name for no particular reason. `:` is not rendered in the settings file, so it might make more sense to use `-` instead or something.
* Fixes #357.
* Even arbitrary ASCII names of devices could lead to a nullptr returned by Windows.
=> Move profile structs to settings object API, change header name

src/main.cpp
We expect a standard 96DPI display rendering when creating the overlay,
but system DPI can interfere with this. Setting
QCoreApplication::setAttribute(Qt::AA_Use96Dpi) resolves this.
https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/issues/369
=> Set a static DPI before rendering in-VR overlay

.circleci/config.yml, src/tabcontrollers/AudioTabController.cpp
fixes #316 
Currently the new audio override keys are unset by default, and can cause some log spam, this change sets them to false, and maintains default behavior, but should prevent spam issues.
=> fixed audio override key unset issues

src/settings/settings_object.h, src/tabcontrollers/ChaperoneTabController.cpp
`m_visibility - m_visibility` is always zero, and so the if statement body is never executed.
```cpp
// getAmountOfSavedObjects() gives the total amount of objects,
// so if we have 2 profiles it will return 2
auto profileCount = getAmountOfSavedObjects( o );
// Since we start at one, we'll need <= and not < to not miss the last item
for ( int profileNumber = 1; profileNumber <= profileCount; ++profileNumber )
```
=> Fix visibility not being set, and off by one error when loading settings

.circleci/config.yml, .travis.yml, build_scripts/qt/sources.pri, docs/building_for_linux.md, src/tabcontrollers/AudioTabController.cpp, src/tabcontrollers/audiomanager/AudioManagerPulse.cpp, src/tabcontrollers/audiomanager/AudioManagerPulse.h, src/tabcontrollers/audiomanager/AudioManagerPulse_internal.h
* Adds microphone controls on Linux via PulseAudio (PA) for several points in https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/issues/43.
It can not be overstated how unsuited the public AudioManager API is for using the PA API.
It can also not be overstated how undocumented and horrible the PA API is. The PA way of doing audio is very unlike the Windows way of doing audio, which the AudioManager is heavily influenced by.
Since I don't have a Linux machine I have not been able to personally test this. https://github.com/feilen/ has graciously helped with testing.
PulseAudio is very undocumented and not very widely used for what we need outside of official utilities. As such there's most likely a better way of doing things than I've done.
Additional information can be …
=> Implement microphone controls for Linux/PulseAudio

.appveyor.yml, .circleci/config.yml, .travis.yml, advancedSettings.pro, build_scripts/qt/compilers/clang-gcc-common-switches.pri, build_scripts/qt/compilers/clang.pri, build_scripts/qt/compilers/gcc.pri
* Fixes #398 
* Fixes a few of the points in #396.
The clang Travis server does not have the gold linker plugin installed, which means it can't compile with LTO on. The LTO lines are removed in the Travis build script, but regular Clang builds are still compiled with LTO on.
=> Refactor CI and add Linux compiler optimizations

src/overlaycontroller.cpp, src/overlaycontroller.h, src/res/qml/SettingsPage.qml, src/res/qml/video_page/brightness/BrightnessGroupBox.qml, src/tabcontrollers/VideoTabController.cpp
fixes #410 
fixes default value of brightness caused by initialization issues w/ overlay.
Adds a  "shutdown" button to settings.... that shuts down OVRAS, and not SteamVR
=> Fix default Brightness value/behavior adds shutdown button

src/keyboard_input/input_sender.h, src/keyboard_input/input_sender_X11.cpp, src/keyboard_input/input_sender_win.cpp, src/keyboard_input/keyboard_input.cpp
* Moves the main logic of `keyboard_input/input_sender` to a cross platform file, in order to reduce duplication.
* Fixes a Linux bug where keys would not be released due to `TOKEN_NO_KEYUP_NEXT`
* Fixes a bug where premade key combinations that required holding one key did not work correctly (Alt+Tab, Alt+Enter, Ctrl+c, Ctrl+v).
=> Refactor keyboard input sender

build_scripts/linux/appimage.sh
This prevented the appimage from working on newer Manjaro versions.
It has also been tested on Debian Testing to still work there.
Apparently pushes the bottom of the screen out of the overlay on Manjaro, but it's better than having it immediately segfault.
AppVeyor fails due to storage limit.
Fixes #437.
=> Add exclution of libxcb-randr.so.0 to AppImage

build_scripts/linux/appimage.sh, src/tabcontrollers/ChaperoneTabController.h
* Fixes #455 
* Fixes #456.
The problems in #450 _could_ be related to the chaperone profiles being out of whack.
More information for either issue in the commit text.
This also highlights how tedious and unnecessarily complex debugging the settings object API is.
=> Fix chaperone profiles not loading correctly and SEGFAULT with Linux appimage

build_scripts/qt/sources.pri, src/alarm_clock/vr_alarm.cpp, src/overlaycontroller.cpp, src/overlaycontroller.h, src/tabcontrollers/AudioTabController.cpp, src/tabcontrollers/AudioTabController.h, src/tabcontrollers/ChaperoneTabController.cpp, src/tabcontrollers/ChaperoneTabController.h, src/tabcontrollers/MoveCenterTabController.cpp, src/tabcontrollers/MoveCenterTabController.h, src/tabcontrollers/SettingsTabController.cpp, src/tabcontrollers/SettingsTabController.h, src/tabcontrollers/SteamVRTabController.cpp, src/tabcontrollers/SteamVRTabController.h, src/tabcontrollers/UtilitiesTabController.cpp, src/tabcontrollers/UtilitiesTabController.h, src/tabcontrollers/VideoTabController.cpp, src/utils/update_rate.cpp, src/utils/update_rate.h
Previous way of controlling when controllers were run was split among the different  controllers, meaning that third parties would require knowledge of internal state of  controllers in order to be on the same update schedule as them.
This refactor moves the logic into a seperate class.
Additionally, it also stops the use of the `adjustUpdateRate` function on all tab controllers, since it broke the prime-number-ability of less collisions.
=> Refactor update rates of tab controllers

build_scripts/linux/appimage.sh, src/package_files/linux/AdvancedSettings.desktop
This PR disables the AppImageLauncher integration. The problem right now is that whenever OVR-AS is started on Steam, AppImageLauncher will ask about starting it once or integrating it into the system.
Related issue and note by the developer of AppImageLauncher:
https://github.com/TheAssassin/AppImageLauncher/issues/338#issuecomment-649001773
=> Disallow AppImageLauncher integration

build_scripts/linux/appimage.sh
`qtdeploylinux` apparently caches the .desktop file, so we need to change both of them.
Issue discovered by @DASPRiD in PR #484, see discussion there for more.
=> Add X-AppImage-Integrate=false to second .desktop file

src/tabcontrollers/RotationTabController.cpp, src/tabcontrollers/RotationTabController.h
Like the title says: when beginning an auto-turn, estimate the frame rate using the last frametime, then apply it (times our turn rate) each frame instead of checking the time delta every frame. Results in somewhat smoother turns, though the chaperone still jitters as it does when using space drag/turn.
=> Smoother (autoturn) smooth turn: estimate frame rate when beginning turn

Readme.md, src/settings/internal/settings_controller.h
Something I've been wanting to do for a while... with Autoturn, snap-turn is the most comfortable option but is super disorienting. Smooth-turn generally gives you a better sense of direction, but the default of 90 deg/s is a bit slow and uncomfortable, some people have mentioned turning it way up so you can see where you've turned but still spending as little time 'in the turn' as possible.
=> Bump up autoturn smooth turn speed default, adjust Readme.md

Readme.md, build_scripts/compile_version_string.txt, src/package_files/action_manifest.json, src/package_files/default_action_manifests/ovras-team.advancedsettings_default_hp_wmr.json, ver/versioncheck.json
**This Is a release PR**
fixes #518 
Adds default Controller Bindings for HP's new WMR controllers (probably)
fixes a formatting Issue in readme.
=> Reverb Bindings and 5.3.1

src/tabcontrollers/UtilitiesTabController.cpp
This is a slight adjustment to the tracker battery overlay position to prevent clipping with the new Vive Tracker 3.0 higher face and closer prongs. These changes shouldn't degrade functionality on other trackers.
Old position:
New position:
=> Adjust tracker battery overlay position for Vive Tracker 3.0

docs/building_for_linux.md
Fixes partially https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/issues/580. AUR package still needs to be updated.
=> Add `qt5-quickcontrols` package to required for Arch

installer/installer.nsi
The [Microsoft Windows Package Manager](/microsoft/winget-cli) relies on registry entries to determine the version of an installed package. This PR causes the Publisher and Version to be set in the ARP table when using the installer file
=> Add Publisher and Version to ARP entry

build_scripts/linux/appimage.sh
On more recent distributions (Debian Testing, Arch, Manjaro), libxkbcommon.so.0 causes segfaults at launch.
=> Exclude libxkbcommon.so.0, causes segfaults

build_scripts/linux/PKGBUILD
It turns out qt5-websockets needs to be included for a successful build.
=> fix PKGBUILD to include missing dependency

build_scripts/linux/PKGBUILD
It turns out qt5-websockets needs to be included for a successful build.
=> fix PKGBUILD to include missing dependency (#606)
