OpenVR-Advanced-Settings/OpenVR-AdvancedSettings

.gitignore, advancedSettings.pro, installer/installer.nsi, src/LICENSE.txt, src/overlaycontroller.cpp, src/res/qml/PlayspacePage.qml, src/tabcontrollers/MoveCenterTabController.cpp, src/tabcontrollers/MoveCenterTabController.h
New Features:
1. added ability to lock axis in play-space mover on chaperone tab
Bug Fixes:
1. fixed save/toggle state of double-click to move and lock playspace buttons
2. updated .nsi script to properly re-create .exe
3. removed some logging as a possible cause of some compositor crashing.
Known issues:
1. logging conf file not included in installer script currently
2. have not updated readme
=> some simple merges/fixes

advancedSettings.pro
removes the extra items added from https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/pull/4
=> cleanup .pro file

.travis.yml, advancedSettings.pro, src/tabcontrollers/ChaperoneTabController.cpp, src/utils/ChaperoneUtils.cpp
- explicitly specify c++11
- use `cmath` instead of `math.h`
=> add travis config for linux ci build

src/ivrinput/ivrinput.cpp, src/ivrinput/ivrinput.h, src/overlaycontroller.cpp, src/package_files/action_manifest.json, src/tabcontrollers/MoveCenterTabController.cpp, src/tabcontrollers/MoveCenterTabController.h
Initial implementation of gravity with floor collision, sideways momentum, and terminal velocity. Some constants such as gravitational acceleration aren't set up with constexpr because I intend them to be customizable when I build the interface.
Known issue is that comfort mode on drag multiplies the velocity because the time-skip of comfort mode isn't taken into account. I'm leaving it like this for now until I build customizable momentum scaling when I get to work on the interface side of things.
Also momentum is "saved" when gravity is toggled off then back on. I'm leaving this functionality also until I build the interface option to have it save or not.
=> Implemented gravity

docs/building_for_linux.md
As discovered on Discord with username223
=> Specify the path that QT will search in

src/package_files/action_manifest.json
When Moving action sets, some of the names weren't properly updated, this fixes that 
* Fixes issue #123
=> Fixed Action Names in Json File

Readme.md, build_scripts/win/common.py, installer/installer.nsi, src/overlaycontroller.h
Updated version number for 3.0.0 Release... and Added default Bindings in readme.
=> Release 3.0.0 Pr Multiple reviews please.

build_scripts/win/common.py, installer/installer.nsi, src/overlaycontroller.h
Prevents issues with logs referring to out of date versions, etc.
=> Update version string to append "-dev"

src/openvr/ivrinput.cpp, src/openvr/ivrinput.h, src/overlaycontroller.cpp, src/package_files/action_manifest.json, src/res/qml/SettingsPage.qml, src/res/qml/motion_page/snap_turn/SnapTurnGroupBox.qml, src/tabcontrollers/MoveCenterTabController.cpp, src/tabcontrollers/MoveCenterTabController.h
Adds some basic features requested from users on our issues page. This specifically addresses #210 and #212
=> Add smooth turn and universe centered rotation

docs/keyboard_input_guide.md
Fixed a naming error from .txt->.md in keyboard_input-guide.md
=> fixed a .txt -> .md

build_scripts/run-clang-format.py
Upstream updated the script with error checking for incorrect clang-format executable.
This is not a current need but it will make debugging errors way easier.
Script just checks that the executable exists before trying to run the executable.
=> Update run-clang-format script

docs/SteamVRInputGuide.md
This was changed by Valve in a recent patch on live SteamVR.
Fixes #309.
=> Update controller binding port in docs

src/res/qml/video_page/color/ColorGroupBox.qml, src/res/qml/video_page/overlaycolorbright/OverlayMethodGroupBox.qml
higher values are only possible via direct textbox input
=> Increase the max gain on color to 9999

build_scripts/compile_version_string.txt, src/tabcontrollers/VideoTabController.cpp, ver/versioncheck.json
Changes the QT settings to color<color>New in order to prevent issues that cause some people to have dim screens on update.
=> changed colors to not default to dim on some systems during upgrade

src/tabcontrollers/AudioTabController.cpp, src/tabcontrollers/AudioTabController.h, src/tabcontrollers/ChaperoneTabController.cpp, src/tabcontrollers/ChaperoneTabController.h, src/tabcontrollers/MoveCenterTabController.cpp, src/tabcontrollers/MoveCenterTabController.h, src/tabcontrollers/SettingsTabController.cpp, src/tabcontrollers/SettingsTabController.h, src/tabcontrollers/SteamVRTabController.cpp, src/tabcontrollers/SteamVRTabController.h, src/tabcontrollers/UtilitiesTabController.cpp, src/tabcontrollers/UtilitiesTabController.h
=> changed m_k_ to m_

src/tabcontrollers/AudioTabController.cpp
=> Fix push to mute icon not being used when PTM enabled

src/overlaycontroller.cpp, src/overlaycontroller.h
=> fixes keyboard positioning

src/openvr/ivrinput.cpp, src/openvr/ivrinput.h, src/package_files/action_manifest.json, src/package_files/default_action_manifests/ovras-team.advancedsettings_default_knuckles.json, src/package_files/default_action_manifests/ovras-team.advancedsettings_default_touch.json, src/package_files/default_action_manifests/ovras-team.advancedsettings_default_vive_controller.json
Hides the "haptic" action set
Creates New Action Set called "System"
Moves haptic clicks to "system"
Fixes non-critical errors w/ default json bindings.
fixes #388
=> Fixes Actions for Future.

src/tabcontrollers/RotationTabController.cpp
- interframe arc-length was calculated wrong, so the magnitude of changes was less than expected
- copy/paste error
=> Fix logic errors in redirected-walking

build_scripts/compile_version_string.txt, docs/SteamVRInputGuide.md, src/main.cpp, src/tabcontrollers/VideoTabController.cpp, src/tabcontrollers/VideoTabController.h, ver/versioncheck.json
- Fixes render bug (hopefully 1 confirmed so far)
- Fixes compatibility issues with sort order of color/brightness
fixes #515
fixes #530 
fixes #528
=> No Render Fix, Color/Brightness Sort Order, readme adjustment
